<?php

$english = array(
	// plugin settings
	'commandline_cron:settings:disable_url' => "Disable URL based CRON",
	
	'commandline_cron:install:title' => "Installation instructions",
	'commandline_cron:install:description' => "In order for you to configure your Elgg site to use the command line cron your hosting provider must allow you to execute PHP on the commandline.<br />
		This plugin is usefull in two situations:<br />
		1. your hosting provider doesn't allow (w)get,<br />
		or 2. you wish to prevent other users from triggering the cron.",
	'commandline_cron:install:commandline' => "Below you'll find an example command line for your Elgg installation.",
	'commandline_cron:install:options' => "There are several command line options you can configure:<br />
		<b>secret (required):</b> this is required and is generated by the system for your Elgg installation<br />
		<b>interval (required):</b> the cron interval, allowed options are %s<br />
		<b>host:</b> the HTTP host of your Elgg installation<br />
		<b>https:</b> wether or not your site is secured<br />
		<b>memory_limit:</b> the maximum allowed memory for PHP to use<br />
		",
	
	// cli
	'commandline_cron:cli:error:secret' => "Invalid secret, please check the plugin settings",
);

add_translation("en", $english);